apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-tpetkos-app-tekton
  namespace: openshift-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/chatbot-tpetkos/overlays/tekton
    repoURL: https://github.com/ai-rolling-demo/chatbot-tpetkos-2025111001-gitops.git
    targetRevision: main
  destination:
    namespace: rhdh-app
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
